/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sisun_kokkiri_sisun_JNIAdapter_FFmpegAdapter */

#ifndef _Included_sisun_kokkiri_sisun_JNIAdapter_FFmpegAdapter
#define _Included_sisun_kokkiri_sisun_JNIAdapter_FFmpegAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sisun_kokkiri_sisun_JNIAdapter_FFmpegAdapter
 * Method:    setDataSource
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_sisun_kokkiri_sisun_JNIAdapter_FFmpegAdapter_setDataSource
  (JNIEnv *, jclass, jstring);

/*
 * Class:     sisun_kokkiri_sisun_JNIAdapter_FFmpegAdapter
 * Method:    play
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_sisun_kokkiri_sisun_JNIAdapter_FFmpegAdapter_play
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
